/**
 * Shared contracts for History of Earth. Every module builds against these.
 * See SPEC.md for the full design. Do not change these shapes without updating SPEC.md.
 */

/* ───────────────────────────── Time ───────────────────────────── */

/**
 * YEAR CONVENTION (used everywhere):
 *   - A plain number on one continuous axis.
 *   - Positive = CE (1492 = 1492 CE). Negative = BCE (-3500 = 3500 BCE).
 *   - Deep time is simply a large negative number: -66_000_000 = 66 million years ago.
 *   - There is no "year zero" special-casing; the axis is treated as continuous.
 *   - Fractional years are allowed (used during playback; 1914.58 ≈ August 1914).
 */
export type Year = number;

/** Solar System / Earth begins forming (CAI age). Timeline start. */
export const TIMELINE_START: Year = -4_567_000_000;
/** Earth's accretion essentially complete. */
export const EARTH_FORMATION_YEAR: Year = -4_540_000_000;
/** Timeline end ("now"). Updated at runtime by TimeModel.presentYear(). */
export const PRESENT_YEAR: Year = 2026.75;

/* ───────────────────────────── Events ───────────────────────────── */

export type EventCategory =
  | 'cosmic'          // solar system, impacts, Moon, orbital/astronomical
  | 'geology'         // tectonics, continents, volcanism, rocks
  | 'climate'         // ice ages, snowball, warming, atmosphere changes
  | 'life'            // origin and evolution of life, key organisms
  | 'extinction'      // mass extinctions
  | 'human-evolution' // hominins, Homo sapiens, migrations before civilization
  | 'civilization'    // cities, states, agriculture, writing
  | 'empire'          // rise/fall of states and empires, conquests
  | 'war'             // wars, battles, revolutions with violence
  | 'politics'        // treaties, constitutions, political change
  | 'religion'        // religions, philosophies, reforms
  | 'science'         // discoveries, theories
  | 'technology'      // inventions, engineering, infrastructure
  | 'exploration'     // voyages, expeditions, space exploration
  | 'culture'         // art, literature, monuments, sport
  | 'economy'         // trade, finance, plagues' economic effects
  | 'disaster'        // earthquakes, eruptions, pandemics, famines
  | 'fringe';         // ONLY for fringe/pseudo-historical claims (see consensus)

/**
 * How well-supported the claim is:
 *  - established: textbook consensus
 *  - majority: mainstream view with minor dissent / dating uncertainty
 *  - debated: genuine active scientific/historical debate (both sides credible)
 *  - fringe: rejected by mainstream scholarship; included for interest and clearly labelled.
 *            MUST include `mainstreamView`.
 */
export type Consensus = 'established' | 'majority' | 'debated' | 'fringe';

export interface HistoryEvent {
  /** Unique kebab-case id, prefixed with the era file name, e.g. "mesozoic-chicxulub-impact". */
  id: string;
  /** ≤ 60 characters. */
  title: string;
  /** Start year (see YEAR CONVENTION). For a point event this is the event's year. */
  year: Year;
  /** End year for spans (wars, dynasties, periods). Omit for point events. */
  endYear?: Year;
  /** Human-readable date override, e.g. "c. 4.51 billion years ago", "11 November 1918". */
  dateLabel?: string;
  /** ± uncertainty in years, when dating is approximate. */
  uncertainty?: number;
  /** Focus location (WGS84 degrees). For planet-wide events pick a representative spot AND set global=true. */
  lat: number;
  lon: number;
  /** True when the event affects the whole planet (no single location). */
  global?: boolean;
  /**
   * Reconstructed palaeo-position of (lat, lon) at the event's age, from the plate model
   * (generated by scripts/reconstruct-event-points.mjs). Used instead of lat/lon whenever the
   * globe is in 'paleo' mode so deep-time markers sit on the reconstructed continents.
   */
  paleoLat?: number;
  paleoLon?: number;
  category: EventCategory;
  /** 5 = landmark (always visible, used by the Tour), 4 = major, 3 = notable, 2 = minor, 1 = detail. */
  importance: 1 | 2 | 3 | 4 | 5;
  /** One sentence, ≤ 160 chars, for the side-panel card. */
  summary: string;
  /** 2–6 sentences. Mainstream view; mention dating uncertainty or debate where relevant. */
  description: string;
  /** Exact English Wikipedia article title, e.g. "Chicxulub crater". */
  wikipedia?: string;
  consensus: Consensus;
  /** Required when consensus is 'fringe' or 'debated': what mainstream scholarship says and why. */
  mainstreamView?: string;
  tags?: string[];
}

/* ───────────────────────────── Chapters (table of contents) ───────────────────────────── */

export type SchematicKind = 'magma' | 'cooling' | 'waterworld' | 'cratons';
export type AtmosphereKind = 'normal' | 'hazy' | 'orange' | 'thin';

export interface GlobeStyle {
  /**
   * satellite  – modern imagery (NASA Blue Marble / ESRI).
   * paleo      – GPlates reconstructed coastlines for the nearest snapshot (0–1000 Ma).
   * schematic  – procedurally generated illustrative surface (no reliable reconstruction exists).
   */
  mode: 'satellite' | 'paleo' | 'schematic';
  schematic?: SchematicKind;
  /** CSS colors for paleo mode. */
  landColor?: string;
  oceanColor?: string;
  /** Polar ice caps from this latitude poleward (90 = none, 60 = polar caps, 35 = major glaciation, 0 = snowball). */
  iceCapLatitude?: number;
  atmosphere?: AtmosphereKind;
  /** Draw historical political borders (human era). */
  borders?: boolean;
  /** Draw plate boundaries (paleo mode) if available. */
  plateBoundaries?: boolean;
}

export interface PlanetState {
  /** Short approximate strings, e.g. "~0% (none)", "~21%". */
  o2?: string;
  co2?: string;
  temperature?: string;
  seaLevel?: string;
  dayLength?: string;
  life?: string;
  continents?: string;
  humans?: string;
}

export interface Chapter {
  /** Unique kebab-case id. Level-1 ids are fixed (see SPEC.md). */
  id: string;
  title: string;
  subtitle?: string;
  /** Inclusive start year; exclusive end year (end of the last child == end of parent). */
  start: Year;
  end: Year;
  /** 1 = Part (top of the overview scrubber), 2 = Chapter, 3 = Section. */
  level: 1 | 2 | 3;
  /** 2–5 sentences for the era header / TOC. */
  description: string;
  /** What the planet is like during this chapter (approximate, with "~"). */
  planet?: PlanetState;
  /** How to draw the globe. Children inherit missing fields from parents. */
  globeStyle?: Partial<GlobeStyle>;
  /** Default playback rate at 1× speed, in years per second. Deepest matching chapter wins. */
  playbackYearsPerSecond?: number;
  /** Level-1 only: relative width on the overview scrubber. */
  timelineWeight?: number;
  /** Optional camera focus when jumping here. */
  focus?: { lat: number; lon: number; heightKm?: number };
  children?: Chapter[];
}

/* ───────────────────────────── Snapshots served from /public/data ───────────────────────────── */

export interface PaleoIndex {
  model: string;
  /** Snapshot ages in millions of years ago, ascending (0 … 1000). */
  agesMa: number[];
  /** Path template relative to /data/, e.g. "paleo/coastlines_{age}.json". */
  coastlines: string;
  /** Optional plate-boundary template. */
  plateBoundaries?: string;
  attribution: string;
}

export interface BordersIndex {
  /** Snapshot years (YEAR CONVENTION), ascending. */
  years: Year[];
  /** Path template relative to /data/, e.g. "borders/world_{year}.json". */
  file: string;
  attribution: string;
}

/** Normalised properties of every border polygon feature. */
export interface BorderFeatureProps {
  name: string;
  subject?: string;
  partOf?: string;
}

/* ───────────────────────────── App state ───────────────────────────── */

export type Speed = 0.1 | 0.25 | 0.5 | 1 | 2 | 4 | 10 | 25 | 100;

export interface Settings {
  highResImagery: boolean;   // add ESRI World Imagery layer when zoomed in
  lighting: boolean;         // sun lighting on the globe
  showBorders: boolean;      // historical borders (when chapter allows)
  showLabels: boolean;       // border labels
  showMarkers: boolean;      // event markers on globe
  showFringe: boolean;       // include fringe theories in the panel/markers
  minImportance: 1 | 2 | 3 | 4 | 5;  // hide events below this importance
  tour: boolean;             // auto fly to landmark events during playback
}

export interface AppState {
  year: Year;
  playing: boolean;
  speed: Speed;
  /** +1 forward, -1 backward. */
  direction: 1 | -1;
  selectedEventId: string | null;
  /** Ids of events currently shown in the side panel (recent/ongoing/upcoming). */
  visibleEventIds: string[];
  /** Chapter ids from Part → Section containing the current year. */
  chapterPath: string[];
  /** Range shown by the detail ruler. */
  detailRange: [Year, Year];
  tocOpen: boolean;
  settings: Settings;
}
